// GENERATED by scripts/capture-demo-snapshot.mjs — do not edit by hand.
//
// A real capture from the local backend, served by the hosted browser build so a
// visitor sees the interface populated instead of "Backend reconnecting". Every
// record is relabelled data_origin: "illustrative_preview" on the way in, so
// nothing here can be mistaken for observed behaviour.

export const DEMO_SNAPSHOT = {
  "status": {
    "status": "COLLECTING",
    "service": "2Bme local intelligence",
    "local_only": true,
    "data_mode": "synthetic_bootstrap_baseline",
    "seeded_baseline_sessions": 3000,
    "model_version": "behavior-model-v0.1",
    "websocket_clients": 0
  },
  "session": {
    "id": "sess_40c1077f36054055898dec5db4e3521a",
    "title": "Desktop work session",
    "workflow_type": "deep_work",
    "device_id": "device_demo",
    "status": "active",
    "started_at": "2026-09-20T18:22:37.528114",
    "ended_at": null,
    "duration_s": 9.7,
    "event_count": 336,
    "data_origin": "illustrative_preview"
  },
  "metrics": {
    "session_id": "sess_40c1077f36054055898dec5db4e3521a",
    "task_id": null,
    "session_title": "Desktop work session",
    "workflow_type": "deep_work",
    "duration_s": 3402.1865,
    "friction": 0.1972,
    "focus": 0.7487,
    "automation_potential": 0.3994,
    "confidence": 0.8634,
    "behavior_label": "focused_or_low_friction",
    "evidence": {
      "app_switches_per_min": 0.9876,
      "backtrack_rate": 0,
      "repeated_action_ratio": 1,
      "workflow_repeat_count": 19,
      "keystrokes_per_min": 0,
      "predictable_sequence_score": 0.8328,
      "model_version": "behavior-model-v0.1",
      "baseline_workflow_type": "deep_work",
      "bootstrap_baseline_weight": 0.8,
      "personal_baseline_weight": 0.2,
      "observed_task_count": 1
    },
    "data_origin": "illustrative_preview",
    "model_version": "behavior-model-v0.1",
    "has_live_data": true,
    "created_at": "2026-09-20T18:22:37.635908"
  },
  "metricHistory": [
    {
      "session_id": "sess_40c1077f36054055898dec5db4e3521a",
      "task_id": null,
      "session_title": "Desktop work session",
      "workflow_type": "deep_work",
      "duration_s": 3402.1865,
      "friction": 0.1849,
      "focus": 0.7491,
      "automation_potential": 0.3631,
      "confidence": 0.7614,
      "behavior_label": "focused_or_low_friction",
      "evidence": {
        "app_switches_per_min": 0.9805,
        "backtrack_rate": 0,
        "repeated_action_ratio": 0.98,
        "workflow_repeat_count": 5,
        "keystrokes_per_min": 0,
        "predictable_sequence_score": 0.8384,
        "model_version": "behavior-model-v0.1",
        "baseline_workflow_type": "deep_work",
        "bootstrap_baseline_weight": 0.8,
        "personal_baseline_weight": 0.2,
        "observed_task_count": 1
      },
      "data_origin": "illustrative_preview",
      "model_version": "behavior-model-v0.1",
      "has_live_data": true,
      "created_at": "2026-09-20T18:22:37.606539"
    },
    {
      "session_id": "sess_40c1077f36054055898dec5db4e3521a",
      "task_id": null,
      "session_title": "Desktop work session",
      "workflow_type": "deep_work",
      "duration_s": 3402.1865,
      "friction": 0.19,
      "focus": 0.7488,
      "automation_potential": 0.3919,
      "confidence": 0.8501,
      "behavior_label": "focused_or_low_friction",
      "evidence": {
        "app_switches_per_min": 0.9719,
        "backtrack_rate": 0,
        "repeated_action_ratio": 1,
        "workflow_repeat_count": 11,
        "keystrokes_per_min": 0,
        "predictable_sequence_score": 0.8392,
        "model_version": "behavior-model-v0.1",
        "baseline_workflow_type": "deep_work",
        "bootstrap_baseline_weight": 0.8,
        "personal_baseline_weight": 0.2,
        "observed_task_count": 1
      },
      "data_origin": "illustrative_preview",
      "model_version": "behavior-model-v0.1",
      "has_live_data": true,
      "created_at": "2026-09-20T18:22:37.618908"
    },
    {
      "session_id": "sess_40c1077f36054055898dec5db4e3521a",
      "task_id": null,
      "session_title": "Desktop work session",
      "workflow_type": "deep_work",
      "duration_s": 3402.1865,
      "friction": 0.1954,
      "focus": 0.7486,
      "automation_potential": 0.3994,
      "confidence": 0.8631,
      "behavior_label": "focused_or_low_friction",
      "evidence": {
        "app_switches_per_min": 0.9908,
        "backtrack_rate": 0,
        "repeated_action_ratio": 1,
        "workflow_repeat_count": 17,
        "keystrokes_per_min": 0,
        "predictable_sequence_score": 0.8328,
        "model_version": "behavior-model-v0.1",
        "baseline_workflow_type": "deep_work",
        "bootstrap_baseline_weight": 0.8,
        "personal_baseline_weight": 0.2,
        "observed_task_count": 1
      },
      "data_origin": "illustrative_preview",
      "model_version": "behavior-model-v0.1",
      "has_live_data": true,
      "created_at": "2026-09-20T18:22:37.628548"
    },
    {
      "session_id": "sess_40c1077f36054055898dec5db4e3521a",
      "task_id": null,
      "session_title": "Desktop work session",
      "workflow_type": "deep_work",
      "duration_s": 3402.1865,
      "friction": 0.1972,
      "focus": 0.7487,
      "automation_potential": 0.3994,
      "confidence": 0.8634,
      "behavior_label": "focused_or_low_friction",
      "evidence": {
        "app_switches_per_min": 0.9876,
        "backtrack_rate": 0,
        "repeated_action_ratio": 1,
        "workflow_repeat_count": 19,
        "keystrokes_per_min": 0,
        "predictable_sequence_score": 0.8328,
        "model_version": "behavior-model-v0.1",
        "baseline_workflow_type": "deep_work",
        "bootstrap_baseline_weight": 0.8,
        "personal_baseline_weight": 0.2,
        "observed_task_count": 1
      },
      "data_origin": "illustrative_preview",
      "model_version": "behavior-model-v0.1",
      "has_live_data": true,
      "created_at": "2026-09-20T18:22:37.635908"
    }
  ],
  "rhythm": {
    "session_id": "sess_40c1077f36054055898dec5db4e3521a",
    "span_minutes": 60,
    "window_seconds": 425,
    "points": [
      {
        "at": "2026-09-20T17:26:12.074990+00:00",
        "minutes_ago": 55.1,
        "focus": 0.7024,
        "friction": 0.1844,
        "confidence": 0.6997,
        "keystrokes_per_min": 0,
        "events": 12
      },
      {
        "at": "2026-09-20T17:27:46.563727+00:00",
        "minutes_ago": 53.5,
        "focus": 0.6876,
        "friction": 0.1943,
        "confidence": 0.6794,
        "keystrokes_per_min": 0,
        "events": 21
      },
      {
        "at": "2026-09-20T17:29:21.052464+00:00",
        "minutes_ago": 52,
        "focus": 0.6967,
        "friction": 0.1887,
        "confidence": 0.682,
        "keystrokes_per_min": 0,
        "events": 32
      },
      {
        "at": "2026-09-20T17:30:55.541201+00:00",
        "minutes_ago": 50.4,
        "focus": 0.6897,
        "friction": 0.1931,
        "confidence": 0.6787,
        "keystrokes_per_min": 0,
        "events": 39
      },
      {
        "at": "2026-09-20T17:32:30.029938+00:00",
        "minutes_ago": 48.8,
        "focus": 0.687,
        "friction": 0.1961,
        "confidence": 0.676,
        "keystrokes_per_min": 0,
        "events": 45
      },
      {
        "at": "2026-09-20T17:34:04.518675+00:00",
        "minutes_ago": 47.2,
        "focus": 0.687,
        "friction": 0.1954,
        "confidence": 0.6753,
        "keystrokes_per_min": 0,
        "events": 41
      },
      {
        "at": "2026-09-20T17:35:39.007411+00:00",
        "minutes_ago": 45.7,
        "focus": 0.6861,
        "friction": 0.1967,
        "confidence": 0.671,
        "keystrokes_per_min": 0,
        "events": 41
      },
      {
        "at": "2026-09-20T17:37:13.496148+00:00",
        "minutes_ago": 44.1,
        "focus": 0.6825,
        "friction": 0.1984,
        "confidence": 0.6673,
        "keystrokes_per_min": 0,
        "events": 41
      },
      {
        "at": "2026-09-20T17:38:47.984885+00:00",
        "minutes_ago": 42.5,
        "focus": 0.6886,
        "friction": 0.1944,
        "confidence": 0.6701,
        "keystrokes_per_min": 0,
        "events": 41
      },
      {
        "at": "2026-09-20T17:40:22.473622+00:00",
        "minutes_ago": 40.9,
        "focus": 0.6928,
        "friction": 0.1919,
        "confidence": 0.6812,
        "keystrokes_per_min": 0,
        "events": 43
      },
      {
        "at": "2026-09-20T17:41:56.962359+00:00",
        "minutes_ago": 39.4,
        "focus": 0.6948,
        "friction": 0.1901,
        "confidence": 0.6824,
        "keystrokes_per_min": 0,
        "events": 39
      },
      {
        "at": "2026-09-20T17:43:31.451096+00:00",
        "minutes_ago": 37.8,
        "focus": 0.6914,
        "friction": 0.1926,
        "confidence": 0.6763,
        "keystrokes_per_min": 0,
        "events": 40
      },
      {
        "at": "2026-09-20T17:45:05.939833+00:00",
        "minutes_ago": 36.2,
        "focus": 0.6972,
        "friction": 0.1885,
        "confidence": 0.6843,
        "keystrokes_per_min": 0,
        "events": 40
      },
      {
        "at": "2026-09-20T17:46:40.428570+00:00",
        "minutes_ago": 34.6,
        "focus": 0.6951,
        "friction": 0.1896,
        "confidence": 0.6813,
        "keystrokes_per_min": 0,
        "events": 39
      },
      {
        "at": "2026-09-20T17:48:14.917307+00:00",
        "minutes_ago": 33.1,
        "focus": 0.6972,
        "friction": 0.1887,
        "confidence": 0.6858,
        "keystrokes_per_min": 0,
        "events": 41
      },
      {
        "at": "2026-09-20T17:49:49.406044+00:00",
        "minutes_ago": 31.5,
        "focus": 0.6983,
        "friction": 0.1882,
        "confidence": 0.6881,
        "keystrokes_per_min": 0,
        "events": 42
      },
      {
        "at": "2026-09-20T17:51:23.894781+00:00",
        "minutes_ago": 29.9,
        "focus": 0.6941,
        "friction": 0.1912,
        "confidence": 0.6842,
        "keystrokes_per_min": 0,
        "events": 45
      },
      {
        "at": "2026-09-20T17:52:58.383517+00:00",
        "minutes_ago": 28.3,
        "focus": 0.6891,
        "friction": 0.194,
        "confidence": 0.6793,
        "keystrokes_per_min": 0,
        "events": 44
      },
      {
        "at": "2026-09-20T17:54:32.872254+00:00",
        "minutes_ago": 26.8,
        "focus": 0.6883,
        "friction": 0.1942,
        "confidence": 0.6787,
        "keystrokes_per_min": 0,
        "events": 45
      },
      {
        "at": "2026-09-20T17:56:07.360991+00:00",
        "minutes_ago": 25.2,
        "focus": 0.6945,
        "friction": 0.1899,
        "confidence": 0.6855,
        "keystrokes_per_min": 0,
        "events": 44
      },
      {
        "at": "2026-09-20T17:57:41.849728+00:00",
        "minutes_ago": 23.6,
        "focus": 0.6913,
        "friction": 0.1927,
        "confidence": 0.6825,
        "keystrokes_per_min": 0,
        "events": 46
      },
      {
        "at": "2026-09-20T17:59:16.338465+00:00",
        "minutes_ago": 22,
        "focus": 0.6904,
        "friction": 0.1934,
        "confidence": 0.6815,
        "keystrokes_per_min": 0,
        "events": 45
      },
      {
        "at": "2026-09-20T18:00:50.827202+00:00",
        "minutes_ago": 20.5,
        "focus": 0.6988,
        "friction": 0.1879,
        "confidence": 0.6903,
        "keystrokes_per_min": 0,
        "events": 44
      },
      {
        "at": "2026-09-20T18:02:25.315939+00:00",
        "minutes_ago": 18.9,
        "focus": 0.6943,
        "friction": 0.1912,
        "confidence": 0.6844,
        "keystrokes_per_min": 0,
        "events": 45
      },
      {
        "at": "2026-09-20T18:03:59.804676+00:00",
        "minutes_ago": 17.3,
        "focus": 0.6903,
        "friction": 0.1933,
        "confidence": 0.679,
        "keystrokes_per_min": 0,
        "events": 43
      },
      {
        "at": "2026-09-20T18:05:34.293413+00:00",
        "minutes_ago": 15.7,
        "focus": 0.6857,
        "friction": 0.1956,
        "confidence": 0.6734,
        "keystrokes_per_min": 0,
        "events": 42
      },
      {
        "at": "2026-09-20T18:07:08.782150+00:00",
        "minutes_ago": 14.2,
        "focus": 0.6923,
        "friction": 0.1917,
        "confidence": 0.6789,
        "keystrokes_per_min": 0,
        "events": 37
      },
      {
        "at": "2026-09-20T18:08:43.270887+00:00",
        "minutes_ago": 12.6,
        "focus": 0.6869,
        "friction": 0.1951,
        "confidence": 0.6728,
        "keystrokes_per_min": 0,
        "events": 40
      },
      {
        "at": "2026-09-20T18:10:17.759624+00:00",
        "minutes_ago": 11,
        "focus": 0.6935,
        "friction": 0.1911,
        "confidence": 0.679,
        "keystrokes_per_min": 0,
        "events": 36
      },
      {
        "at": "2026-09-20T18:11:52.248360+00:00",
        "minutes_ago": 9.4,
        "focus": 0.6894,
        "friction": 0.194,
        "confidence": 0.6747,
        "keystrokes_per_min": 0,
        "events": 39
      },
      {
        "at": "2026-09-20T18:13:26.737097+00:00",
        "minutes_ago": 7.9,
        "focus": 0.6925,
        "friction": 0.1914,
        "confidence": 0.6794,
        "keystrokes_per_min": 0,
        "events": 38
      },
      {
        "at": "2026-09-20T18:15:01.225834+00:00",
        "minutes_ago": 6.3,
        "focus": 0.6898,
        "friction": 0.1936,
        "confidence": 0.6777,
        "keystrokes_per_min": 0,
        "events": 42
      },
      {
        "at": "2026-09-20T18:16:35.714571+00:00",
        "minutes_ago": 4.7,
        "focus": 0.6842,
        "friction": 0.1964,
        "confidence": 0.6674,
        "keystrokes_per_min": 0,
        "events": 38
      },
      {
        "at": "2026-09-20T18:18:10.203308+00:00",
        "minutes_ago": 3.1,
        "focus": 0.6809,
        "friction": 0.1991,
        "confidence": 0.6665,
        "keystrokes_per_min": 0,
        "events": 42
      },
      {
        "at": "2026-09-20T18:19:44.692045+00:00",
        "minutes_ago": 1.6,
        "focus": 0.6826,
        "friction": 0.1983,
        "confidence": 0.6671,
        "keystrokes_per_min": 0,
        "events": 41
      },
      {
        "at": "2026-09-20T18:21:19.180782+00:00",
        "minutes_ago": 0,
        "focus": 0.6898,
        "friction": 0.1935,
        "confidence": 0.6775,
        "keystrokes_per_min": 0,
        "events": 42
      }
    ]
  },
  "sessions": [
    {
      "id": "sess_40c1077f36054055898dec5db4e3521a",
      "title": "Desktop work session",
      "workflow_type": "deep_work",
      "device_id": "device_demo",
      "status": "active",
      "started_at": "2026-09-20T18:22:37.528114",
      "ended_at": null,
      "duration_s": 9.7,
      "event_count": 336,
      "data_origin": "illustrative_preview"
    }
  ],
  "workflows": [
    {
      "id": "wf_1fd36e43517c484880785df6d005ed81",
      "name": "Jira → Visual Studio Code → Terminal workflow",
      "workflow_type": "deep_work",
      "steps": [
        {
          "application": "Jira",
          "action": "switch"
        },
        {
          "application": "Visual Studio Code",
          "action": "switch"
        },
        {
          "application": "Terminal",
          "action": "switch"
        }
      ],
      "repeat_count": 19,
      "average_duration_s": 195.80876,
      "predictability": 0.8328,
      "automation_potential": 0.3994,
      "confidence": 0.8634,
      "data_origin": "illustrative_preview"
    }
  ],
  "recommendations": [],
  "privacy": {
    "application_activity": true,
    "window_switching": true,
    "window_titles": false,
    "browser_context": true,
    "keyboard_timing": true,
    "clipboard_metadata": false,
    "visual_interpretation": false,
    "terminal_activity": true,
    "ai_analysis": true
  },
  "plan": {
    "id": "plan_c0e564da9ac04cae9bbb8303a970d0c4",
    "workflow_id": "wf_1fd36e43517c484880785df6d005ed81",
    "actions": [
      {
        "type": "open_application",
        "application": "Jira"
      },
      {
        "type": "open_application",
        "application": "Visual Studio Code"
      },
      {
        "type": "open_application",
        "application": "Terminal"
      },
      {
        "type": "prepare_context",
        "workflow_id": "wf_1fd36e43517c484880785df6d005ed81"
      }
    ],
    "required_permissions": [
      "open_application",
      "read_active_window"
    ],
    "safety_level": 1,
    "status": "awaiting_approval",
    "intent": {
      "connector": "desktop",
      "operation": "open_application",
      "resource": "workflow:wf_1fd36e43517c484880785df6d005ed81",
      "params": {
        "destination": "preview_only",
        "applications": [
          "Jira",
          "Visual Studio Code",
          "Terminal"
        ],
        "actions": [
          "open_application",
          "open_application",
          "open_application",
          "prepare_context"
        ]
      }
    },
    "risk": "low"
  },
  "assistant": {
    "answer": "The same privacy-safe sequence appeared 19 times. The configured repetition, predictability, and confidence gates were met. Prepare the repeated steps as a reviewable assisted workflow. Automation potential is 40 with 86% model confidence.",
    "category": "automation",
    "grounded_in": {
      "workflow": {
        "name": "Jira → Visual Studio Code → Terminal workflow",
        "repeat_count": 19,
        "average_duration_s": 195.80876
      },
      "behavior": {
        "friction": 0.1972,
        "focus": 0.7487,
        "automation_potential": 0.3994,
        "confidence": 0.8634
      },
      "evidence": {
        "app_switches_per_min": 0.9876,
        "backtrack_rate": 0,
        "repeated_action_ratio": 1,
        "workflow_repeat_count": 19,
        "keystrokes_per_min": 0,
        "predictable_sequence_score": 0.8328,
        "observed_task_count": 1
      }
    },
    "has_live_data": true,
    "model_version": "behavior-model-v0.1",
    "data_origin": "illustrative_preview",
    "suggested_action": null
  },
  "briefing": {
    "text": "Your current focus score is 75, with friction at 20. I found a reviewable workflow that appeared 19 times. You can open its draft, but running it will still require Touch ID.",
    "sections": [
      {
        "label": "Now",
        "text": "Your current focus score is 75, with friction at 20."
      },
      {
        "label": "Next",
        "text": "I found a reviewable workflow that appeared 19 times. You can open its draft, but running it will still require Touch ID."
      }
    ],
    "grounded_in": {
      "workflow": {
        "name": "Jira → Visual Studio Code → Terminal workflow",
        "repeat_count": 19,
        "average_duration_s": 195.80876
      },
      "behavior": {
        "friction": 0.1972,
        "focus": 0.7487,
        "automation_potential": 0.3994,
        "confidence": 0.8634
      },
      "evidence": {
        "app_switches_per_min": 0.9876,
        "backtrack_rate": 0,
        "repeated_action_ratio": 1,
        "workflow_repeat_count": 19,
        "keystrokes_per_min": 0,
        "predictable_sequence_score": 0.8328,
        "observed_task_count": 1
      }
    },
    "generated_at": "2026-09-20T18:22:47.245855+00:00",
    "has_live_data": true,
    "model_version": "behavior-model-v0.1"
  }
};
